# Generated by Django 4.2.13 on 2024-07-02 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graf', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='is_leave',
            field=models.BooleanField(default=False),
        ),
    ]
