# Generated by Django 4.2.13 on 2024-07-03 04:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('graf', '0003_remove_schedule_is_leave_schedule_day_of_week_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='graf.address'),
        ),
    ]
