# Generated by Django 4.2.13 on 2024-07-03 04:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('graf', '0004_alter_schedule_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='address',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='graf.address'),
        ),
    ]
